<a href="https://colab.research.google.com/github/raz0208/Natural-Language-Processing-Practices/blob/main/TopicModelling/NLP_TopicsModellingPractices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Topic Modelling Practices in NLP


1. Semantic Signal Separation
2. KeyNMF
3. ClusteringTopicModel

### 1. Semantic Signal Separation

In [ ]:
!pip install -q transformers datasets huggingface_hub

In [ ]:
from huggingface_hub import login

login("")

In [ ]:
# Install turftopic libraries
!pip install turftopic
!pip install datasets

In [ ]:
# import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from turftopic import SemanticSignalSeparation
from datasets import load_dataset
from sentence_transformers import SentenceTransformer

In [ ]:
# Read and load dataset
ds = pd.read_csv('political_ideologies_train.csv')
texts = ds["statement"]

print(texts)

0       Climate change, and the escalating environment...
1       I believe in the foundational importance of th...
2       I firmly believe that the principle of separat...
3       I firmly believe in the separation of church a...
4       I firmly believe in the power of free markets ...
                              ...
2555    I believe in the power of free markets to driv...
2556    I firmly believe in the traditional family str...
2557    Every individual, regardless of their gender, ...
2558    I firmly believe in the significance of religi...
2559    I firmly believe in the principle of individua...
Name: statement, Length: 2560, dtype: object

In [ ]:
ds

,statement,label,issue_type,__index_level_0__
0,"Climate change, and the escalating environment...",1,1,465
1,I believe in the foundational importance of th...,0,2,1191
2,I firmly believe that the principle of separat...,1,6,2440
3,I firmly believe in the separation of church a...,1,6,2406
4,I firmly believe in the power of free markets ...,0,0,1903
...,...,...,...,...
2555,I believe in the power of free markets to driv...,0,0,1907
2556,I firmly believe in the traditional family str...,0,2,1139
2557,"Every individual, regardless of their gender, ...",1,7,48
2558,I firmly believe in the significance of religi...,1,6,822
2559,I firmly believe in the principle of individua...,0,0,1979

In [ ]:
encoder = SentenceTransformer('paraphrase-MiniLM-L12-v2')
embeddings = encoder.encode(texts, show_progress_bar=True)

In [ ]:
print(embeddings)

[[-0.20092632  0.33961082  0.02055947 ... -0.14055775 -0.09066175
  -0.05947793]
 [-0.05251725  0.2111203  -0.2350792  ... -0.19393641  0.06882618
  -0.02158776]
 [-0.06461112  0.07165432 -0.08635489 ... -0.05988945  0.02278206
   0.0677686 ]
 ...
 [ 0.2636646   0.07064892 -0.10288888 ...  0.00702172  0.0945406
  -0.02747649]
 [ 0.2114343   0.13071813 -0.26949868 ... -0.00532549 -0.03988217
  -0.08325328]
 [-0.3067356   0.26985478 -0.18770279 ... -0.16361783  0.10027055
  -0.09515021]]

In [ ]:
model = SemanticSignalSeparation(4, encoder=encoder, random_state=42)
doc_topic_matrix = model.fit_transform(texts, embeddings=embeddings)

In [ ]:
model.print_topics(top_k=10)

┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Topic ID ┃ Topic Name         ┃ Highest Ranking                        ┃ Lowest Ranking                         ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│        0 │ Religiosity        │ warming, carbon, environment, solar,   │ wealth, taxation, prosperity,          │
│          │                    │ change, planet, greenhouse,            │ wealthiest, tax, profit, taxes,        │
│          │                    │ environmental, shift, fossil           │ entrepreneurship, fiscal, government   │
├──────────┼────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┤
│        1 │ Economic vs Social │ religious, religion, church,           │ spending, fiscal, budget, economic,    │
│          │                    │ religions, faith, faiths, respectful,  │ economies, economy, growth,            │
│          │                    │ respect, distinct, lgbtq               │ investments, economically, productive  │
├──────────┼────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┤
│        2 │ Environmentalism   │ marriage, structure, traditions,       │ healthcare, medical, patient, health,  │
│          │                    │ relationships, structures, tradition,  │ care, healthy, treated, healthier,     │
│          │                    │ tensions, conflicts, conflict, couples │ treatment, treatments                  │
├──────────┼────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┤
│        3 │ Personality        │ freedoms, liberties, iran, freedom,    │ households, adoption, racial,          │
│          │                    │ faith, religion, protection, secure,   │ household, racism, families,           │
│          │                    │ military, security                     │ ethnicity, mothers, childcare, races   │
└──────────┴────────────────────┴────────────────────────────────────────┴────────────────────────────────────────┘

In [ ]:
model.plot_concept_compass(0, 1)

In [ ]:
model.rename_topics({
    0: "Religiosity",
    1: "Economic vs Social",
    2: "Environmentalism",
    3: "Personality"
})

In [ ]:
model.print_topic_distribution("I am a socialist and I am concerned with the growing inequality in our societies. I'd like to see governments do more to prevent the exploitation of workers.")

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Topic name         ┃ Score ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━┩
│ Environmentalism   │  0.09 │
│ Personality        │  0.03 │
│ Religiosity        │ -1.13 │
│ Economic vs Social │ -1.32 │
└────────────────────┴───────┘

In [ ]:
import plotly.express as px

df = pd.DataFrame(doc_topic_matrix, columns=model.topic_names)
df["party"] = ["Liberal" if label == 1 else "Conservative" for label in ds["label"]]

fig = px.scatter_matrix(df, dimensions=model.topic_names, color="party", template="plotly_white", width=1000, height=1100)
fig = fig.update_traces(diagonal_visible=False, showupperhalf=False, marker=dict(opacity=0.6))
fig.show()

### 3. Clustering Analysing
#### Building a Taxonomy of Machine Learning Papers

In [ ]:
!pip install -U datasets
# !pip install datasets
!pip install turftopic[umap-learn]
!pip install turftopic[datamapplot]
#!pip install top2vec[visualization]

In [15]:
# import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import torch

# From turftopic import SemanticSignalSeparation
from datasets import load_dataset
from sentence_transformers import SentenceTransformer
from turftopic import Top2Vec
from turftopic import BERTopic

In [2]:
print("CUDA available:", torch.cuda.is_available())
print("GPU count:", torch.cuda.device_count())
print("Device name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")
print("-------"*10)
!nvidia-smi

CUDA available: True
GPU count: 1
Device name: Tesla T4
----------------------------------------------------------------------
Fri Jun 13 18:35:37 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
# Read and load dataset from huggingface
ds1 = load_dataset("CShorten/ML-ArXiv-Papers", split="train")

# Subsampling dataset
ds1 = ds1.train_test_split(seed=42, test_size=10000)["test"]

abstracts1 = ds1["abstract"]

In [4]:
# show the number of abstracts
print(f"The number of abstracts: {len(abstracts1)}", "\n")

abstracts1[:5]

The number of abstracts: 10000

["  In this paper we propose $\\epsilon$-Consistent Mixup ($\\epsilon$mu).\n$\\epsilon$mu is a data-based structural regularization technique that combines\nMixup's linear interpolation with consistency regularization in the Mixup\ndirection, by compelling a simple adaptive tradeoff between the two. This\nlearnable combination of consistency and interpolation induces a more flexible\nstructure on the evolution of the response across the feature space and is\nshown to improve semi-supervised classification accuracy on the SVHN and\nCIFAR10 benchmark datasets, yielding the largest gains in the most challenging\nlow label-availability scenarios. Empirical studies comparing $\\epsilon$mu and\nMixup are presented and provide insight into the mechanisms behind\n$\\epsilon$mu's effectiveness. In particular, $\\epsilon$mu is found to produce\nmore accurate synthetic labels and more confident predictions than Mixup.\n",
 '  Autoencoders have useful applications in high energy physics in anomaly\ndetection, particularly for jets - collimated showers of particles produced in\ncollisions such as those at the CERN Large Hadron Collider. We explore the use\nof graph-based autoencoders, which operate on jets in their "particle cloud"\nrepresentations and can leverage the interdependencies among the particles\nwithin a jet, for such tasks. Additionally, we develop a differentiable\napproximation to the energy mover\'s distance via a graph neural network, which\nmay subsequently be used as a reconstruction loss function for autoencoders.\n',
 "  Exciting contemporary machine learning problems have recently been phrased in\nthe classic formalism of tree search -- most famously, the game of Go.\nInterestingly, the state-space underlying these sequential decision-making\nproblems often posses a more general latent structure than can be captured by a\ntree. In this work, we develop a probabilistic framework to exploit a search\nspace's latent structure and thereby share information across the search tree.\nThe method is based on a combination of approximate inference in jointly\nGaussian models for the explored part of the problem, and an abstraction for\nthe unexplored part that imposes a reduction of complexity ad hoc. We\nempirically find our algorithm to compare favorably to existing\nnon-probabilistic alternatives in Tic-Tac-Toe and a feature selection\napplication.\n",
 '  Around the globe, ticks are the culprit of transmitting a variety of\nbacterial, viral and parasitic diseases. The incidence of tick-borne diseases\nhas drastically increased within the last decade, with annual cases of Lyme\ndisease soaring to an estimated 300,000 in the United States alone. As a\nresult, more efforts in improving lesion identification approaches and\ndiagnostics for tick-borne illnesses is critical. The objective for this study\nis to build upon the approach used by Burlina et al. by using a variety of\nconvolutional neural network models to detect tick-borne skin lesions. We\nexpanded the data inputs by acquiring images from Google in seven different\nlanguages to test if this would diversify training data and improve the\naccuracy of skin lesion detection. The final dataset included nearly 6,080\nimages and was trained on a combination of architectures (ResNet 34, ResNet 50,\nVGG 19, and Dense Net 121). We obtained an accuracy of 80.72% with our model\ntrained on the DenseNet 121 architecture.\n',
 '  Deep neural networks have gained tremendous importance in many computer\nvision tasks. However, their power comes at the cost of large amounts of\nannotated data required for supervised training. In this work we review and\ncompare different techniques available in the literature to improve training\nresults without acquiring additional annotated real-world data. This goal is\nmostly achieved by applying annotation-preserving transformations to existing\ndata or by synthetically creating more data.\n']

In [ ]:
# # Using TurfTopic default encoder to extract embedding of the dataset
encoder1 = SentenceTransformer("all-MiniLM-L6-v2")
embeddings1 = encoder1.encode(abstracts1, show_progress_bar=True)

In [7]:
# create a dataframe for 5 first embeddings
df = pd.DataFrame(embeddings1[:])
df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.116793,-0.048010,0.013904,0.020555,0.102551,-0.002297,-0.001540,-0.038846,-0.093981,-0.128632,...,0.091226,-0.072464,-0.044301,-0.079422,0.023961,0.064886,0.045012,-0.055690,-0.015406,0.007885
1,-0.113509,-0.063588,0.045744,0.069508,0.023963,0.004733,0.011323,-0.020639,0.009974,-0.052237,...,0.004441,0.046467,-0.005209,-0.106404,0.055330,0.031162,-0.015407,0.052612,-0.079166,0.000951
2,-0.046366,-0.062943,0.076053,0.008464,0.087632,0.004908,0.033890,-0.041043,-0.004651,0.000576,...,0.064989,0.014189,0.044394,-0.055709,0.007850,-0.015040,0.030750,-0.056158,0.009977,0.046114
3,-0.022161,-0.081515,0.074852,-0.008076,0.074276,0.006316,0.020354,0.036162,-0.047043,-0.030080,...,0.005349,-0.080112,-0.053862,-0.055705,-0.007194,0.128456,0.031168,0.002715,-0.018317,0.006816
4,-0.024045,-0.038111,0.033548,-0.041262,0.083008,0.015470,0.010767,-0.093849,-0.008791,-0.086870,...,0.003405,-0.008197,-0.003859,-0.026671,0.040897,0.136462,-0.033441,-0.023917,-0.017840,-0.013066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.022007,-0.025172,-0.025964,0.005955,0.110572,-0.008803,-0.000628,-0.105988,-0.049180,0.014990,...,0.056070,-0.001756,-0.081871,-0.042868,0.103274,-0.039233,0.051121,0.031668,-0.014564,-0.033605
9996,-0.148666,-0.023369,0.058389,0.028600,-0.004698,0.016038,-0.013862,-0.040023,-0.053083,-0.051324,...,-0.025992,-0.010671,-0.037332,-0.074483,-0.027046,0.029448,0.001782,0.074415,0.054203,0.036414
9997,0.005107,-0.029706,0.023024,0.019745,0.017944,-0.002686,0.021389,-0.052526,-0.008535,-0.053164,...,-0.058315,-0.001612,0.014443,-0.068842,-0.024539,0.051659,-0.013413,-0.011464,-0.118150,-0.031719
9998,-0.015600,-0.075435,-0.010884,-0.048085,-0.022817,-0.014012,0.013586,-0.009622,-0.004461,0.013935,...,0.094178,-0.030854,0.029789,-0.050457,0.061554,0.031880,-0.026690,-0.003210,-0.051809,-0.011401
9999,-0.003975,-0.047182,0.063209,0.034229,0.143885,-0.071996,0.004362,-0.054605,0.004716,0.083217,...,0.074266,0.017063,0.029080,-0.138315,0.001008,0.040171,0.036012,-0.045512,-0.049121,-0.032086

In [8]:
# # show rows 127, 223, 319
# df.iloc[[127, 223, 319]]

In [9]:
print(embeddings1, embeddings1.shape)

[[-0.1167931  -0.04801036  0.01390377 ... -0.05568971 -0.01540568
   0.00788483]
 [-0.11350863 -0.06358757  0.04574388 ...  0.05261219 -0.07916622
   0.00095109]
 [-0.04636589 -0.06294328  0.07605291 ... -0.0561576   0.00997735
   0.04611383]
 ...
 [ 0.00510686 -0.02970619  0.02302423 ... -0.01146424 -0.11814963
  -0.03171895]
 [-0.01559985 -0.07543531 -0.01088388 ... -0.00320966 -0.05180904
  -0.01140063]
 [-0.00397541 -0.04718209  0.06320886 ... -0.04551153 -0.04912112
  -0.032086  ]] (10000, 384)

### Read saved embedding dataset from root

In [12]:
# # save the embedding in a csv file
# np.savetxt("Cluster_Analysis_Default_DS_Embeddings.csv", embeddings, delimiter=",")

In [ ]:
# # Read and load dataset
# emb_ds1 = pd.read_csv('Cluster_Analysis_Default_DS_Embeddings.csv')

# embeddings = emb_ds1.to_numpy()

# print(embeddings, embeddings.shape)

In [23]:
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# embeddings1_Sc = scaler.fit_transform(embeddings1)

# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# embeddings_MMc = scaler.fit_transform(embeddings1)

In [9]:
# embeddings_Sc

In [ ]:
!pip install bertopic

from bertopic import BERTopic

In [ ]:
model = BERTopic(encoder=encoder1, random_state=42)
topic_data = model.prepare_topic_data(abstracts1, embeddings=embeddings1)

In [17]:
model.print_topics()

┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Topic ID ┃ Highest Ranking                                                                                      ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│       -1 │ data, model, learning, models, neural, based, network, training, image, networks                     │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        0 │ quantum, classical, circuit, qubit, machine, circuits, computers, hamiltonian, noise, near           │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        1 │ delivery, problem, routing, graph, combinatorial, traveling, facility, problems, driver, requests    │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        2 │ players, sports, player, team, game, teams, playing, match, matches, games                           │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        3 │ voltage, grid, drl, simplex, energy, operation, control, power, policy, marl                         │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        4 │ financial, trading, portfolio, market, reinforcement, asset, price, profit, agent, rl                │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        5 │ drl, scheduling, resource, wireless, service, radio, reinforcement, channel, vehicles, 5g            │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        6 │ fairness, fair, groups, bias, discrimination, unfairness, decision, algorithmic, sensitive, group    │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        7 │ forgetting, continual, catastrophic, cl, memory, tasks, incremental, lifelong, task, new             │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        8 │ revenue, price, auction, advertising, ad, auctions, ads, pricing, products, bid                      │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│        9 │ channel, wireless, receiver, modulation, iot, csi, communication, coding, snr, decoding              │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       10 │ games, equilibrium, game, nash, agents, sum, players, agent, player, regret                          │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       11 │ localization, indoor, location, positioning, csi, position, smartphone, wireless, meters, wall       │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       12 │ gnns, attacks, graph, gnn, attack, adversarial, graphs, node, robustness, defense                    │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       13 │ policy, rl, reinforcement, reward, agent, policies, robot, control, action, planning                 │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       14 │ agent, agents, marl, team, opponent, reinforcement, multi, centralized, incentive, policies          │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       15 │ privacy, private, differential, differentially, varepsilon, mechanism, sample, complexity, alpha,    │
│          │ bounds                                                                                               │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       16 │ attacks, privacy, sensitive, membership, leakage, apis, defense, victim, bert, risks                 │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       17 │ drl, attacks, attack, reinforcement, policies, adversarial, cooperative, adversary, vulnerabilities, │
│          │ backdoor                                                                                             │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       18 │ bandit, armed, regret, agents, arm, texttt, reward, players, arms, local                             │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       19 │ intrusion, traffic, detection, attacks, cyber, ids, attack, security, anomaly, benign                │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       20 │ fraud, transaction, money, malicious, financial, banking, orders, detection, transactions, alert     │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       21 │ bandit, regret, bandits, arm, arms, armed, thompson, bound, contextual, reward                       │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       22 │ regret, forecaster, online, bounds, experts, expert, hints, losses, bound, feedback                  │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       23 │ causal, discovery, variables, causality, graphical, effects, structure, conditional, variable,       │
│          │ graphs                                                                                               │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       24 │ causal, treatment, confounders, observational, outcome, effect, confounding, effects,                │
│          │ counterfactual, unobserved                                                                           │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       25 │ privacy, private, dp, preserving, differential, differentially, encrypted, secure, homomorphic, data │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       26 │ federated, fl, clients, privacy, client, server, local, communication, devices, distributed          │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       27 │ bo, optimization, bayesian, objective, hyperparameter, acquisition, functions, black, cost, function │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       28 │ communication, distributed, compression, participation, compressed, byzantine, convergence,          │
│          │ variance, contractive, bottleneck                                                                    │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       29 │ sgd, asynchronous, communication, convergence, stochastic, gradient, distributed, delay, descent,    │
│          │ delays                                                                                               │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       30 │ malware, detection, families, malicious, detectors, api, evade, execution, apps, attacks             │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       31 │ adversarial, attacks, attack, robustness, examples, perturbations, defense, box, robust, training    │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       32 │ control, nonlinear, safety, controllers, safe, systems, controller, lyapunov, stability, contraction │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       33 │ teacher, distillation, student, kd, knowledge, compression, dna, group, assistant, model             │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       34 │ face, facial, recognition, biometric, faces, images, bias, verification, image, softmax              │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       35 │ covid, 19, pandemic, infected, infections, spread, epidemic, health, countries, forecasting          │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       36 │ patient, clinical, patients, health, survival, medical, ehr, mortality, disease, care                │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       37 │ clustering, cluster, unsupervised, deep, clusters, latent, vae, discriminative, dc, representation   │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       38 │ activity, wearable, ecg, gait, sensor, signals, recognition, har, activities, subjects               │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       39 │ eeg, sleep, signals, brain, subject, bci, electroencephalography, subjects, electroencephalogram,    │
│          │ classification                                                                                       │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       40 │ crowd, crowdsourcing, workers, worker, crowdsourced, budget, annotation, annotators, annotator,      │
│          │ labeling                                                                                             │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       41 │ text, handwritten, handwriting, characters, layout, recognition, scene, capsule, dataset, digits     │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       42 │ credit, risk, financial, default, companies, customers, loan, banking, regulation, public            │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       43 │ recommendation, recommender, item, user, items, users, recommendations, systems, cold, collaborative │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       44 │ ranking, rankings, scores, items, bipartite, lists, ranked, item, rank, utility                      │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       45 │ software, bug, projects, coverage, ml, project, bugs, test, testing, code                            │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       46 │ explanations, explanation, counterfactual, interpretability, ai, explainable, black, human, models,  │
│          │ interpretable                                                                                        │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       47 │ hmm, hidden, markov, em, series, hmms, leakage, states, sequence, membership                         │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       48 │ ising, marginals, belief, graphical, propagation, partition, graphs, polynomial, norm, min           │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       49 │ bayesian, structure, graphical, structures, score, independence, variables, markov, conditional, bn  │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       50 │ rbm, symmetry, boltzmann, restricted, equivariant, lattice, breaking, ising, visible, likelihood     │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       51 │ brain, functional, fmri, cognitive, disease, mri, imaging, magnetic, resonance, connectivity         │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       52 │ spiking, snns, neurons, neuromorphic, spike, sensory, brain, snn, plasticity, neural                 │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       53 │ emotion, facial, recognition, multimodal, emotions, expression, emotional, modalities, valence,      │
│          │ expressions                                                                                          │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       54 │ inverse, phase, reconstruction, compressive, recovery, measurements, generative, sensing, imaging,   │
│          │ problems                                                                                             │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       55 │ galaxy, spectrum, simulations, angular, matter, power, weak, maps, radio, masses                     │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       56 │ seismic, velocity, subsurface, wave, inversion, cnns, cnn, reservoir, fluid, imaging                 │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       57 │ protein, drug, molecules, chemical, molecular, molecule, graph, drugs, proteins, prediction          │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       58 │ stock, market, financial, price, stocks, volatility, prices, forecasting, assets, trading            │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       59 │ material, materials, strain, atomic, solid, properties, property, diffraction, peaks, symmetry       │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       60 │ design, stress, element, cad, material, fiber, topology, materials, designs, mechanical              │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       61 │ power, ac, grid, flow, violations, voltage, measurements, worst, load, estimation                    │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       62 │ chaotic, dynamics, dynamical, chaos, odes, ode, equations, local, kalman, systems                    │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       63 │ anomaly, detection, anomalies, outlier, anomalous, series, outliers, normal, abnormal, data          │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       64 │ reconstruction, mri, artifacts, imaging, cs, resolution, mr, artifact, images, diagnostic            │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       65 │ ct, dose, imaging, radiation, reconstruction, tomography, images, image, artifacts, spectral         │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       66 │ particle, physics, particles, detector, energy, beam, detectors, timing, collisions, event           │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       67 │ process, event, logs, mining, discovery, intervention, business, prediction, log, historical         │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       68 │ logic, reasoning, logical, programs, boolean, program, inductive, sat, programming, relational       │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       69 │ code, language, programs, programming, source, program, languages, editing, token, summarization     │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       70 │ students, student, education, courses, online, teaching, educational, knowledge, comments, tracing   │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       71 │ hyperbolic, manifold, euclidean, geometry, riemannian, curvature, topological, spaces, manifolds,    │
│          │ space                                                                                                │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       72 │ series, time, forecasting, ts, transformer, multivariate, rnns, sequences, event, spectrum           │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       73 │ covid, 19, chest, ct, pneumonia, ray, disease, diagnosis, coronavirus, images                        │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       74 │ fluid, velocity, physical, flow, laws, physics, particle, field, pressure, mechanics                 │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       75 │ equations, pdes, differential, pinns, equation, pde, physics, informed, solution, partial            │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       76 │ traffic, temporal, travel, transportation, prediction, spatial, road, demand, urban, city            │
├──────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────┤
│       77 │ driving, vehicle, vehicles, autonomous, trajectory, driver, trajectories, motion, traffic, lane      │

In [18]:
model.reduce_topics(n_reduce_to=25)
print(model.hierarchy.cut(3))

Root:
├── -1: learning, data, model, based, models, neural, training, network, method, performance
├── 0: quantum, classical, learning, machine, circuit, qubit, noise, algorithms, circuits, algorithm
├── 2: players, sports, game, player, team, teams, playing, match, games, matches
├── 56: seismic, data, velocity, cnn, cnns, wave, subsurface, noise, inversion, imaging
├── 66: physics, particle, detector, particles, energy, high, beam, reconstruction, event, detectors
├── 67: process, event, mining, logs, prediction, discovery, intervention, log, business, models
├── 115: nas, search, architecture, architectures, neural, performance, space, cifar, network,
│   training
├── 122: mixture, mixtures, gaussians, gaussian, algorithm, distributions, reduction, univariate,
│   binomial, parameters
├── 123: ot, transport, optimal, sinkhorn, wasserstein, regularized, algorithm, problem, measures,
│   plan
├── 136: nmf, matrix, nonnegative, factorization, matrices, data, gene, ontology, factorizations,
│   rank
├── 141: normalization, batch, training, bn, activations, initialization, variance, networks, dropout,
│   neural
├── 146: topic, topics, document, words, model, models, documents, dirichlet, modeling, word
├── 168: covid, 19, chest, ct, pneumonia, disease, ray, pandemic, cases, data
│   ├── 35: covid, 19, pandemic, infected, infections, spread, health, epidemic,
│   │   countries, forecasting
│   └── 73: covid, 19, chest, ct, pneumonia, ray, disease, diagnosis, coronavirus,
│       images
├── 176: pruning, network, networks, accuracy, pruned, neural, filter, parameters, sparsity, filters
│   ├── 131: sparsity, pruning, sparse, network, parameters, centroids, budgets, sensitivity,
│   │   initialization, parameter
│   └── 132: pruning, pruned, filter, filters, prune, cnns, compression, accuracy, compact, network
├── 220: recommendation, recommender, user, items, item, users, systems, ranking, recommendations,
│   collaborative
│   ├── 43: recommendation, recommender, user, item, items, users, recommendations, systems,
│   │   collaborative, cold
│   └── 44: ranking, rankings, scores, items, bipartite, lists, ranked, item, rank, utility
├── 232: programs, code, probabilistic, programming, logic, program, reasoning, language, learning,
│   inference
│   ├── 69: code, language, programming, programs, source, program, languages, editing, token,
│   │   summarization
│   └── 225: probabilistic, logic, programs, programming, reasoning, program, logical, inference,
│       boolean, synthesis
│       ├── 68: logic, reasoning, logical, programs, boolean, program, inductive, programming, sat,
│       │   learning
│       └── 104: probabilistic, programs, programming, conditioning, program, inference, stochastic,
│           synthesis, interface,
│           synthesizing
├── 235: student, teacher, distillation, knowledge, students, kd, model, compression, data, models
│   ├── 33: teacher, distillation, student, kd, knowledge, compression, dna, model, group, assistant
│   └── 70: students, student, education, online, courses, teaching, knowledge, educational, process,
│       comments
├── 267: equivariant, sr, equivariance, invariant, transformations, symmetry, group, invariance,
│   networks, neural
│   ├── 50: rbm, symmetry, boltzmann, restricted, equivariant, lattice, network, likelihood, neural,
│   │   breaking
│   └── 105: sr, equivariant, equivariance, transformations, invariant, invariance, group, rotations,
│       convolutional,
│       translation
├── 283: financial, price, stock, market, prices, model, revenue, fraud, time, data
│   ├── 234: fraud, credit, financial, risk, transaction, banking, transactions, detection, customers,
│   │   money
│   │   ├── 20: fraud, transaction, money, detection, malicious, financial, orders, banking,
│   │   │   transactions, alert
│   │   └── 42: credit, risk, financial, default, companies, customers, loan, banking, public,
│   │       regulation
│   └── 259: price, stock, market, financial, prices, revenue, volatility, stocks, advertising,
│       auction
│       ├── 8: revenue, price, advertising, auction, ad, ads, auctions, pricing, products, demand
│       └── 179: stock, market, financial, price, prices, volatility, stocks, trading, forecasting,
│           series
├── 289: material, design, materials, simulations, galaxy, model, network, neural, computational,
│   data
│   ├── 55: galaxy, spectrum, simulations, power, angular, matter, weak, maps, neural, density
│   └── 195: material, design, materials, stress, computational, strain, properties, element, elastic,
│       topology
│       ├── 59: material, materials, strain, atomic, properties, solid, property, diffraction, peaks,
│       │   symmetry
│       └── 60: design, stress, element, cad, material, topology, fiber, materials, designs,
│           mechanical
├── 290: learning, domain, data, tasks, active, meta, task, classification, training, label
│   ├── 271: class, boosting, classification, drift, ensemble, classifier, trees, classifiers, forest,
│   │   tree
│   │   ├── 118: drift, concept, ensemble, classifier, stream, time, leaf, reuse, data, forgetting
│   │   └── 224: class, boosting, classification, trees, forest, classifiers, ensemble, tree,
│   │       classifier, decision
│   └── 284: learning, domain, tasks, data, active, meta, task, label, labels, adaptation
│       ├── 264: active, label, labels, learning, supervised, semi, unlabeled, labeled, data, noisy
│       └── 275: domain, learning, tasks, meta, task, adaptation, forgetting, source, shot, target
├── 292: learning, policy, algorithm, function, algorithms, optimization, problem, methods, data,
│   reinforcement
│   ├── 277: policy, learning, reinforcement, rl, algorithm, reward, agent, algorithms, stochastic,
│   │   problem
│   │   ├── 243: stochastic, gradient, convergence, convex, optimization, sgd, problems, descent,
│   │   │   algorithm, rate
│   │   └── 245: policy, reinforcement, rl, learning, reward, agent, regret, policies, algorithm,
│   │       agents
│   └── 287: data, causal, neural, networks, bayesian, function, inference, model, learning, models
│       ├── 165: causal, treatment, effect, observational, variables, effects, confounders, outcome,
│       │   data, confounding
│       └── 285: neural, data, networks, bayesian, function, kernel, functions, variational, model,
│           learning
├── 293: graph, clustering, data, graphs, node, gnns, learning, methods, protein, networks
│   ├── 279: manifold, metric, nearest, distance, data, dimensional, hashing, neighbor, similarity,
│   │   hyperbolic
│   │   ├── 178: manifold, hyperbolic, dimensional, data, topological, manifolds, space, euclidean,
│   │   │   dimensionality, geometry
│   │   └── 236: metric, nearest, hashing, distance, neighbor, hash, similarity, learning, binary,
│   │       neighbors
│   └── 280: graph, clustering, graphs, node, gnns, data, protein, drug, learning, network
│       ├── 196: clustering, clusters, cluster, means, algorithm, data, community, algorithms,
│       │   communities, problem
│       └── 254: graph, gnns, node, graphs, protein, drug, gnn, embedding, nodes, molecules
├── 294: language, models, translation, word, question, attention, tasks, transformer, task, text
│   ├── 161: summary, summaries, summarization, language, news, metrics, references, pretraining,
│   │   wikipedia, reference
│   └── 268: language, translation, models, word, question, attention, transformer, tasks, text,
│       task
│       ├── 124: dialogue, dialog, conversational, conversation, language, responses, conversations,
│       │   human, chat, response
│       └── 258: language, translation, question, word, models, attention, transformer, text, tasks,
│           qa
├── 295: adversarial, privacy, attacks, attack, data, federated, training, learning, model,
│   detection
│   ├── 219: privacy, federated, fl, private, data, learning, clients, model, differential, client
│   │   ├── 26: federated, fl, clients, privacy, client, server, local, communication, devices,
│   │   │   distributed
│   │   └── 206: privacy, private, differential, differentially, dp, preserving, sensitive, data,
│   │       varepsilon, attacks
│   └── 281: adversarial, attacks, attack, detection, anomaly, robustness, examples, training, defense,
│       perturbations
│       ├── 30: malware, detection, families, malicious, detectors, attacks, api, classification,
│       │   feature, classifiers
│       └── 266: adversarial, attacks, attack, anomaly, detection, robustness, examples, training,
│           defense, perturbations
└── 298: model, data, based, learning, models, network, deep, using, training, performance
    ├── 296: data, model, based, models, speech, learning, using, image, training, deep
    │   ├── 221: 3d, lidar, point, pose, object, camera, detection, depth, clouds, estimation
    │   └── 291: data, model, speech, models, based, learning, using, image, training, deep
    └── 297: traffic, network, time, deep, neural, based, learning, driving, model, memory
        ├── 257: series, time, recurrent, sequence, hidden, networks, neural, models, rnns, long
        └── 286: traffic, network, deep, driving, based, learning, neural, performance, prediction,
            memory

In [19]:
fig = model.hierarchy.plot_tree()
fig.show()

In [21]:
fig = model.hierarchy[298].plot_tree()
fig.show()

In [26]:
# We will reset the hierarchy, so that we can see all topics at once.
model.reset_topics()
fig = model.plot_clusters_datamapplot(hover_text=ds1["title"])
fig.show()

In [23]:
# create a dataframe for 5 first embeddings
df = pd.DataFrame(embeddings1[:])
df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.116793,-0.048010,0.013904,0.020555,0.102551,-0.002297,-0.001540,-0.038846,-0.093981,-0.128632,...,0.091226,-0.072464,-0.044301,-0.079422,0.023961,0.064886,0.045012,-0.055690,-0.015406,0.007885
1,-0.113509,-0.063588,0.045744,0.069508,0.023963,0.004733,0.011323,-0.020639,0.009974,-0.052237,...,0.004441,0.046467,-0.005209,-0.106404,0.055330,0.031162,-0.015407,0.052612,-0.079166,0.000951
2,-0.046366,-0.062943,0.076053,0.008464,0.087632,0.004908,0.033890,-0.041043,-0.004651,0.000576,...,0.064989,0.014189,0.044394,-0.055709,0.007850,-0.015040,0.030750,-0.056158,0.009977,0.046114
3,-0.022161,-0.081515,0.074852,-0.008076,0.074276,0.006316,0.020354,0.036162,-0.047043,-0.030080,...,0.005349,-0.080112,-0.053862,-0.055705,-0.007194,0.128456,0.031168,0.002715,-0.018317,0.006816
4,-0.024045,-0.038111,0.033548,-0.041262,0.083008,0.015470,0.010767,-0.093849,-0.008791,-0.086870,...,0.003405,-0.008197,-0.003859,-0.026671,0.040897,0.136462,-0.033441,-0.023917,-0.017840,-0.013066
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-0.022007,-0.025172,-0.025964,0.005955,0.110572,-0.008803,-0.000628,-0.105988,-0.049180,0.014990,...,0.056070,-0.001756,-0.081871,-0.042868,0.103274,-0.039233,0.051121,0.031668,-0.014564,-0.033605
9996,-0.148666,-0.023369,0.058389,0.028600,-0.004698,0.016038,-0.013862,-0.040023,-0.053083,-0.051324,...,-0.025992,-0.010671,-0.037332,-0.074483,-0.027046,0.029448,0.001782,0.074415,0.054203,0.036414
9997,0.005107,-0.029706,0.023024,0.019745,0.017944,-0.002686,0.021389,-0.052526,-0.008535,-0.053164,...,-0.058315,-0.001612,0.014443,-0.068842,-0.024539,0.051659,-0.013413,-0.011464,-0.118150,-0.031719
9998,-0.015600,-0.075435,-0.010884,-0.048085,-0.022817,-0.014012,0.013586,-0.009622,-0.004461,0.013935,...,0.094178,-0.030854,0.029789,-0.050457,0.061554,0.031880,-0.026690,-0.003210,-0.051809,-0.011401
9999,-0.003975,-0.047182,0.063209,0.034229,0.143885,-0.071996,0.004362,-0.054605,0.004716,0.083217,...,0.074266,0.017063,0.029080,-0.138315,0.001008,0.040171,0.036012,-0.045512,-0.049121,-0.032086

In [24]:
# Calculate the Standard deviation for df
std_dev = np.std(df, axis=0)

std_dev

0      0.044472
1      0.044867
2      0.041396
3      0.042194
4      0.048787
         ...
379    0.047914
380    0.044293
381    0.044813
382    0.043120
383    0.040686
Length: 384, dtype: float32

In [25]:
# Print starndard deviations approximately 0
std_dev[std_dev < 0.0001]

127    0.000000e+00
223    0.000000e+00
319    5.260577e-09
dtype: float32

In [39]:
mean = np.mean(df, axis=0)
mean

0     -0.050614
1     -0.051454
2      0.021106
3      0.017747
4      0.040029
         ...
379    0.041593
380    0.007266
381    0.006576
382   -0.039145
383   -0.000415
Length: 384, dtype: float32

In [40]:
print("Minimum std deviation across dimensions:", np.min(std_dev))
print("Minimum mean across dimensions:", np.min(mean))
print("Maximum mean across dimensions:", np.max(mean))

Minimum std deviation across dimensions: 0.05091680958867073
Minimum mean across dimensions: -0.07107391953468323
Maximum mean across dimensions: 0.07737497240304947